### ISSUE TITLE
'DDXMLPrivate.h' file not found

### ISSUE THREAD

**Issue by AndroidBirdBoom** [robbiehanson/KissXML#100]
hi , when i add KissXML to my Podfile and open my project, he  shows this:

WhirlyGlobe/WhirlyGlobeSrc/local_libs/KissXML/DDXMLDocument.m:1:9: 'DDXMLPrivate.h' file not found

anybody can help me?
thinks

**Comment by CommonYun** [comment]
me too,How did you solve it

**Comment by panshouheng** [comment]
Me too, How can I fix it? Thanks!

**Comment by AndroidBirdBoom** [comment]
add #import <libxml/parser.h> in KissXML/DDXMLDocument.m 
直接在 KissXML/DDXMLDocument.m中引入#import <libxml/parser.h>就可以解决了

**Comment by AndroidBirdBoom** [comment]
i found this answer from https://github.com/mousebird/WhirlyGlobe/issues/1034
