### ISSUE TITLE
DDXMLNode:XMLString can't handle unicode

### ISSUE THREAD

**Issue by qiulang** [robbiehanson/KissXML#36]
Hi I find that DDXMLNode:XMLString can't handle unicode case, it will return string with unicode point &#x...

Just check this simple case,

DDXMLNode *node = [DDXMLNode attributeWithName:@"name" stringValue:@"我"];
NSLog(@"%@",[node XMLString]);

The output is "name="& # x6211;"  // I have to add some space in between here otherwise my browser will convert to the corresponding unicode character

I have check the code but but have no idea how to fix it.

**Comment by AtemTeng** [comment]
+1,how to solve?

**Comment by Feng999** [comment]
+1, any idea?

**Comment by colemancda** [comment]
Same here:

```
DDXMLElement *element = [DDXMLElement elementWithName:@"testElement" stringValue:@"😎"];
NSLog(@"%@", element.description);
[element addAttribute:[DDXMLNode attributeWithName:@"testAttribute" stringValue:@"😎"]];
NSLog(@"%@", element.description);
```

Produces:
```
<testElement>😎</testElement>
<testElement testAttribute="&#x1F60E;">😎</testElement>
```
