### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by wujiandao07** [robbiehanson/KissXML#49]
Just now I downLoad this file and I found the iOS Demo can not complie,  @import libxml;

**Comment by davidchiles** [comment]
What iOS Demo Project? The tests require `pod install`.

**Comment by wujiandao07** [comment]
Thank you davidchiles  .
The iPhoneXMPP Demo on Xcode7.2 can not compile in file DDXMLNode.h  First Loading I found Xcode give me "Use of  @import when Modules are disabled" and 14 Errors,  but  when I set Enable Modules  YES   then Xcode give me Module "libxml" not found.

**Comment by chrisballinger** [comment]
Try 5.1.0
