### ISSUE TITLE
libxml_module with tvos is unsupported

### ISSUE THREAD

**Issue by jondwillis** [robbiehanson/KissXML#56]
The required podspec changes to fix this were already made, but it appears that never made it to the public Cocoapods Specs repo with version 5.0.3.

additionally, the libxml and libxmlSimu modules are pointing to hard-coded paths. is $(SDK_ROOT) not available?

**Comment by chrisballinger** [comment]
Unfortunately SDKROOT doesn't work in modulemaps. If it does, I haven't been able to get it to work. A possible solution could be to use prepare_command to modify a modulemap template with the correct SDK paths.

The latest published podspec should mirror what's in master. I think what might be needed are separate modulemap definitions and ifdefs for tvos / tvos simulator.

**Comment by jondwillis** [comment]
Yes. I went with that approach, introducing `libxmlTVOS` and `libxmlTVOSSimu`, and then changed the imports to something like:

```
#if DDXML_LIBXML_MODULE_ENABLED
#if TARGET_OS_IOS && !TARGET_OS_SIMULATOR
@import libxml;
#elif TARGET_OS_IOS && TARGET_OS_SIMULATOR
@import libxmlSimu;
#if TARGET_OS_TV && !TARGET_OS_SIMULATOR
@import libxmlTVOS;
#elif TARGET_OS_TV && TARGET_OS_SIMULATOR
@import libxmlTVOSSimu;
#elif TARGET_OS_MAC
@import libxmlMac;
#endif
#else
#import <libxml/tree.h>
#endif```

**Comment by chrisballinger** [comment]
Great! If you submit a PR I'll merge it

**Comment by chrisballinger** [comment]
Fixed in a better way in master branch, removing the need for funky modules entirely
