### ISSUE TITLE
Support for Carthage

### ISSUE THREAD

**Issue by marekcirkos** [robbiehanson/KissXML#58]
It would be cool if you could add support for Carthage.
https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

**Comment by marekcirkos** [comment]
https://github.com/robbiehanson/KissXML/pull/60

**Comment by chrisballinger** [comment]
This is something I'll look into again now that we've removed the need for the libxml module.

**Comment by jacobwgillespie** [comment]
Any updates on this?

**Comment by yichizhang** [comment]
https://github.com/yichizhang/KissXML/tree/dev

**Comment by yichizhang** [comment]
This PR seems to have what you need:
https://github.com/robbiehanson/KissXML/pull/43/files

Also you can check my fork:
https://github.com/yichizhang/KissXML/tree/dev
