### ISSUE TITLE
Can't build KissXML/libxml_module using cocoapods integration

### ISSUE THREAD

**Issue by ynnadrules** [robbiehanson/KissXML#59]
I am trying to use KissXML's `libxml_module` subspec as a dependency in my cocoapod, but Xcode ends up not being able to build the module.

Below is the build error:

![kiss-xml-build-error](https://cloud.githubusercontent.com/assets/159161/14464835/77914b5c-0085-11e6-90dc-5b2fbf96204e.png)

That error would seem to indicate that my build settings are wrong, but they actually match the settings from `KissXML/libxml_module`'s podspec. 

What I don't understand is why the `DDXML_LIBXML_MODULE_ENABLED` macrodef ends up being 0 even though the `libxml_module` subspec's `xcconfig` settings explicitly set it to 1 as both part of the 

When `DDXML_LIBXML_MODULE_ENABLED` is 0, in file `KissXML/Core/DDXMLNode.h`, the preprocessor conditionals end up trying to import `libxml/tree.h` (which does exist on my system in the proper places). But because `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES` is `NO`, I get the non-modular import error. 

###### `KissXML/Core/DDXMLNode.h` import conditionals
```objc
#if DDXML_LIBXML_MODULE_ENABLED
#if TARGET_OS_IOS && TARGET_OS_EMBEDDED
@import libxml;
#elif TARGET_IPHONE_SIMULATOR
@import libxmlSimu;
#elif TARGET_OS_MAC
@import libxmlMac;
#endif
#else
#import <libxml/tree.h>
#endif
```

###### `KissXML/libxml_module` subspec snippet
```ruby
s.subspec 'libxml_module' do |ss|
    ss.dependency 'KissXML/Core'
    # ...
    ss.preserve_path = 'libxml/module.modulemap'
    ss.xcconfig     = { 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2 $(PODS_ROOT)/KissXML/libxml "$(PODS_ROOT)/../../../libxml"',
                        'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'NO',
                        'OTHER_CFLAGS' => "$(inherited) -DDDXML_LIBXML_MODULE_ENABLED=1",
                        'OTHER_SWIFT_FLAGS' => "$(inherited) -DDDXML_LIBXML_MODULE_ENABLED"
                      }
  end
```

If in my cocoapod's podspec, I add to the same `OTHER_CFLAGS` settings to the `xcconfig`, I manage to get things trying to import the actual modules, but then the error is that it can't find module `libxmlSimu`.

Running `pod lib lint KissXML.podspec` also fails pretty badly. It reports errors similar issues as I describing above. 

Thanks for taking the time to read this probably over-worded issue!

cc @chrisballinger @robbiehanson

**Comment by chrisballinger** [comment]
You need to use @import KissXML in your Pod, and add some extra stuff to
your podspec:
https://github.com/robbiehanson/XMPPFramework/blob/master/XMPPFramework.podspec#L44

**Comment by ynnadrules** [comment]
Thanks @chrisballinger. I got it working now. I don't understand why those build settings in KissXML's podspec don't get applied to the pod that is including KissXML as a dependency. That's probably a question for the cocoapods team. 

Thanks again

**Comment by chrisballinger** [comment]
Hahaha I know this was kind of a nightmare. Took me like a week of banging my head against the wall, especially the libxml modulemap PODS_ROOT / HEADER_SEARCH_PATHS stuff.
