### ISSUE TITLE
5.0.3 installed via pod but I cant use it in my swift app as it wont compile

### ISSUE THREAD

**Issue by Daij-Djan** [robbiehanson/KissXML#64]
5.0.3 installed via pod but I cant use it in my swift app as it wont compile

main.swift:10:8: Could not build Objective-C module 'KissXML'

then for KissXML

DDXMLNode.h:12:9: Include of non-modular header inside framework module 'KissXML.DDXMLNode'
NSString+DDXML.h:12:9: Include of non-modular header inside framework module 'KissXML.NSString_DDXML'

**Comment by colinhumber** [comment]
Have you tried using the `libxml_module` subspec? Presumably you're using `use_frameworks!` in your Podfile?

**Comment by Daij-Djan** [comment]
yes. i use use_frameworks and havent used any subspec. just the normal/basic pod installation

**Comment by colinhumber** [comment]
If you're using `use_frameworks` you'll need to use the `libxml_module` subspec. Change your pod to read `pod "KissXML/libxml_module"` instead of just `pod "KissXML"`.

**Comment by chrisballinger** [comment]
Thanks @colinhumber! That's the ticket.

We should probably add a "getting started" section to the readme to address this. :)

**Comment by Daij-Djan** [comment]
yes. that'd help ppl like me - guess I could have deduced it from the errors but I was too lazy for THAT I admit

**Comment by colinhumber** [comment]
😄 It's mentioned in the changelog in the read me, sort of... But it's not the clearest.

**Comment by chrisballinger** [comment]
Try 5.1.0!
