### ISSUE TITLE
Can't build KissXML/libxml_module in Xcode 8

### ISSUE THREAD

**Issue by colinhumber** [robbiehanson/KissXML#65]
Compiling a brand new project with the following Podfile seems to ignore the DDXML_LIBXML_MODULE_ENABLED flag and tries to run `#import <libxml/tree.h>` instead of the modules. This setup works as expected in Xcode 7. Presumably it has something to do with the `libxml.modulemap`, it the paths inside point to `/Applications/Xcode.app`, not `Xcode-beta.app`...

```
platform :ios, '9.0'

target 'KissXMLTest' do
  use_frameworks!
  pod 'KissXML/libxml_module'
end
```

![image](https://cloud.githubusercontent.com/assets/104855/16503695/69019f6c-3ed1-11e6-8cbc-4beb9bbfbd91.png)

**Comment by chrisballinger** [comment]
Ohhhhh yes. I'm definitely not happy about how Apple left developers to create their own modulemaps for libxml, CommonCrypto, sqlite, etc. We are also missing modulemaps for a bunch of other platforms like watch and tv.

SQLite.swift has a number of them here: https://github.com/stephencelis/SQLite.swift/blob/master/SQLite.swift.podspec#L35
https://github.com/stephencelis/SQLite.swift/tree/master/CocoaPods

I'm not sure how we could support both easily in the same podspec, but perhaps in the readme we could point people to a Xcode-beta branch? Oh yeah another issue is people running 10.12 and not Xcode-beta, and Xcode-beta and 10.11...

:(

**Comment by colinhumber** [comment]
What I'm a little confused about is why the `#if DDXML_LIBXML_MODULE_ENABLED` check is ignored. I can hack the modulemap to point to Xcode-beta.app, but this check always seems to return false, which forces the `#import <libxml/tree.h>` to run instead of importing the appropriate module.

**Comment by chrisballinger** [comment]
I'm wondering if a better route would be to remove all references to libxml from the public headers. It seems easy to fix in DDXMLNode without breaking backwards compatibility but NSString+DDXML might be trickier because the public API exposes xmlChar directly. Even though xmlChar is just a typedef for unsigned char, I don't see a great way to fix it without introducing tons of warnings into people's projects, or breaking things entirely.

**Comment by colinhumber** [comment]
Might be worth just keeping an eye on as Xcode betas keep coming out. I just installed beta 2, and it introduced more errors that weren't present before.

![image](https://cloud.githubusercontent.com/assets/104855/16597073/46892626-42b4-11e6-92e5-0549092bf313.png)

**Comment by chrisballinger** [comment]
Is there any way it's pulling in two modulemaps for both beta and non-beta? I guess if the ifdef isn't working it's not pulling in anything though..

**Comment by colinhumber** [comment]
I started tinkering with having a nested beta subspec under `libxml_module`, that references a second .modulemap that points to Xcode-beta.app.

```
  s.subspec 'libxml_module' do |ss|
    ss.subspec 'beta' do |beta|
      beta.preserve_path = 'libxml/module-beta.modulemap'
    end
 ...
```
and then 
```
pod "KissXML/libxml_module/beta"
```

**Comment by chrisballinger** [comment]
I thiiink it needs to be named module.modulemap, so perhaps put it in a different folder. You also need to make sure that the modulemap folder path is included in the header search paths: https://github.com/robbiehanson/KissXML/blob/master/KissXML.podspec#L34

**Comment by colinhumber** [comment]
Ya, you're right. I pulled that and just tried changing the paths in module.modulemap to point to Xcode-beta.app and it's still causing issues. Seems like a lot of the issues are just due to the `DDXML_LIBXML_MODULE_ENABLED` being ignored. 😦

**Comment by chrisballinger** [comment]
Maybe Swift 3 changed how they expect preprocessor defines on the command line? Hopefully it's not deprecated...

**Comment by colinhumber** [comment]
I ran the converter and am using Swift 2.3, same issues. Definitely seems
like something changed with preprocessor defines in Xcode 8…

I just noticed in the release notes that there’s a new build setting for
Swift. Doesn’t fix the issue, but something to be aware of, at any rate.

```
 “Active Compilation Conditions” is a new build setting for passing
conditional compilation flags to the Swift compiler. Each element of the
value of this setting passes to swiftc prefixed with ‘-D’, in the same way
the elements of “Preprocessor Macros” pass to clang with the same prefix.
(22457329)
```

On July 5, 2016 at 1:51:56 PM, Chris Ballinger (notifications@github.com)
wrote:

Maybe Swift 3 changed how they expect preprocessor defines on the command
line? Hopefully it's not deprecated...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/robbiehanson/KissXML/issues/65#issuecomment-230583690>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAGZl2QHUXrlwRIm8eWwb9V02t7Xt8ovks5qSrXZgaJpZM4JCk64>
.

**Comment by colinhumber** [comment]
So, it definitely seems like the preprocessor define isn't being handled.

In DDXMLNode.h, I added the following at the top, just to see if the flag was defined, and sure enough, it's not.

```
#ifndef DDXML_LIBXML_MODULE_ENABLED
#error "UNDEFINED"
#endif
```

![image](https://cloud.githubusercontent.com/assets/104855/16598497/8612d240-42bb-11e6-9eeb-5465242e081d.png)

**Comment by chrisballinger** [comment]
Aha! That changelog entry is most likely the cause and possibly an Apple or CocoaPods bug. There is definitely funky stuff that happens when Swift imports Objective-C modules, and I bet that the flags aren't being passed around properly from Swift->ObjC.

I bet it works fine when imported into an Obj-C project (with modules).

**Comment by colinhumber** [comment]
😢  No joy... I'm trying to just build the KissXML framework directly now at it's still failing. Ugh... I'm sure it's gonna end up being one flag that is new or needs flipping to get this working...

**Comment by chrisballinger** [comment]
There's some discussion possibly related to this here: http://stackoverflow.com/questions/24003291/ifdef-replacement-in-swift-language

Try `-D DDXML_LIBXML_MODULE_ENABLED` instead of `-DDDXML_LIBXML_MODULE_ENABLED`

It seems that you also can't set it =1 so we might have to change the obj-c ifdef to be ifdef instead of if.

**Comment by colinhumber** [comment]
So... in order to get rid of the issues with the `#if DDXML_LIBXML_MODULE_ENABLED` check failing, in Xcode 8 I needed to add DDXML_LIBXML_MODULE_ENABLED=1 to the list of Preprocessor Macros, not the OTHER_CFLAGS. 😐  However, now it can't fine the actual modules.

The new compiler must have changed how SWIFT/OTHER_CFLAGS work.

![image](https://cloud.githubusercontent.com/assets/104855/16600744/e30c7eba-42c5-11e6-94ee-c5d365dd10c6.png)

**Comment by colinhumber** [comment]
I had KissXML setup as a local development pod, and the search paths don't pick up the module.modulemap in this config. I think I have a handle on this now. Gonna play around a bit and get this working tonight.

**Comment by chrisballinger** [comment]
You may be interested in my new branch that removes libxml from the public headers entirely:

https://github.com/robbiehanson/KissXML/tree/private_libxml

Seems like a nice way to work around the problem and hopefully doesn't break anything for people. :)

**Comment by colinhumber** [comment]
With `DDXMLPrivate.h` importing <libxml/tree.h>, it's throwing the same error as above. 😞 

![image](https://cloud.githubusercontent.com/assets/104855/16604632/893d8a04-42e4-11e6-8963-d10fbd814dc4.png)

**Comment by colinhumber** [comment]
Added a small fix to the podspec to fix this issue. Tested a clean `pod install` in Xcode 8 with the private_libxml branch with the podspec changes and everything compiles!

Thanks a ton for all the help @chrisballinger! I owe you a beer. 😄 

https://github.com/robbiehanson/KissXML/pull/68

**Comment by chrisballinger** [comment]
Ya no problem! :)

Btw I used to use `itunes_transporter_generator` before I switched to Deliver. Even made an issue 3 years ago: https://github.com/colinhumber/issues/19

**Comment by colinhumber** [comment]
Awesome! Ya, that project died pretty quick after Deliver came out, and rightly so. Deliver is amazing!
