### ISSUE TITLE
Problem with DDXMLNode and NS_ASSUME_NONNULL_BEGIN

### ISSUE THREAD

**Issue by mohammadrhemmati** [robbiehanson/KissXML#77]
In DDXMLNode assumed to be not null while some parameters could be null and in swift I can not send nil as a value.
`+ (id)namespaceWithName:(NSString *)name stringValue:(NSString *)stringValue;` 
It could be change to following
`+ (id)namespaceWithName:(nullable NSString *)name stringValue:(NSString *)stringValue;`

**Comment by chrisballinger** [comment]
Please send a pull request

**Comment by chrisballinger** [comment]
Sorry for the confusion, I thought I made an error annotating the DDXMLNode.h mirror of the NSXMLNode.h API. This must stay as it is unless Apple changes it.
