### ISSUE TITLE
Why this function return different result with the same parameter?

### ISSUE THREAD

**Issue by bw4uf** [robbiehanson/KissXML#81]
I called the function below in my project.However,the variable node is different with the same parameter name.For example,I set name as "name" ，the function below sometimes return "<name/>" and sometimes return "<name></name>".So,What's the problem? And What should I do?

- (id)initWithName:(NSString *)name
{
	// Note: Make every guarantee that genericPtr is not null
	
	xmlNodePtr node = xmlNewNode(NULL, [name xmlChar]);
	if (node == NULL)
	{
		return nil;
	}
	
	return [self initWithElementPrimitive:node owner:nil];
}

**Comment by chrisballinger** [comment]
Can you elaborate a bit and post a snippet of your code? I'm not quite sure what you're describing here.
