### ISSUE TITLE
Xcode 9.3 beta : Declaration of 'xmlKeepBlanksDefault' required

### ISSUE THREAD

**Issue by mrunalthanki** [robbiehanson/KissXML#95]
I am getting errors as below while I am running code on Xcode 9.3 beta version.

Errors : 

> Declaration of 'xmlKeepBlanksDefault' must be imported from module 'libxml2.parser' before it is required

> Implicit declaration of function 'xmlKeepBlanksDefault' is invalid in C99

> Conflicting types for 'xmlParseMemory'

**Comment by chrisballinger** [comment]
Fixed in #94
