### ISSUE TITLE
Warnings and errors have appeared in Xcode 9.3. 

### ISSUE THREAD

**Issue by lenlenlen** [robbiehanson/KissXML#98]
Hi, robbiehanson

Thank you for exposing a useful framework.
I am using this framework with the macOS application.

Warnings and errors have appeared in Xcode 9.3. 
Paste the image of error and warning place.

I am glad if you correspond.
Thank you for reading so far.

![2018-03-30 14 23 53](https://user-images.githubusercontent.com/410073/38125720-7abee4d4-3426-11e8-985d-2e944f8522e6.jpg)

**Comment by ecgbao** [comment]
the same tips

**Comment by fullsailor** [comment]
This was fixed in #94 and released in 5.2.2.

**Comment by lenlenlen** [comment]
Thank you! solved!
